### ISSUE TITLE
Hover Effect in the home page

### ISSUE THREAD

**Issue by prrockzed** [Astrodevil/resource-gallery#23]
In the home page, there are three boxes named : "Access for free", "Github Repo" and "Contribute to ReGala". In the "github repo" box, there is no hover effect, while in the other two, there is minimal hover effect. I can add animation such that while hovering we can see contrast change and highlighting of the hovered box.
![prrockzed 2023-05-23 at 12 45 03 PM](https://github.com/ZeroOctave/resource-gallery/assets/97661506/850d0ab8-a614-4fd9-9037-3187db1e0870)

**Comment by prrockzed** [comment]
I want to work on this issue. Please assign it to me.
@Astrodevil

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by akanksha984** [comment]
Please assign this issue to me
