### ISSUE TITLE
Git Page in the Resource Gallery

### ISSUE THREAD

**Issue by prrockzed** [Astrodevil/resource-gallery#24]
I am planning to add some resources in the git pages like git documentation(documentation is the best place to learn something), git cheatsheet(for people to remember the commands), youtube resources to learn git easily and a Git for Beginners blog(I will write this blog).

The layout of the page will be similar to other pages like javascript and web development.

**Comment by prrockzed** [comment]
I want to work on this issue. Please assign it to me under gssoc23.

**Comment by vk20july** [comment]
@Astrodevil I want to work on this issue under gssoc'23
